services:
  backend:
    container_name: backend-go
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # expose backend ke host
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    container_name: frontend-react
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"  # expose frontend ke host
    depends_on:
      - backend
